### ISSUE TITLE
Use Multiple Cores to Build

### ISSUE THREAD

**Issue by doublesharp** [demesm/sysnodesetup#2]
Hi!

You can build the Syscoin core code faster by specifying multiple cores if they are available with `make -jX` where X is the number of cores. You can find this on Ubuntu with `cat /proc/cpuinfo | grep processor | wc -l`.

```
# speed up builds if you have more cores
make -j$(cat /proc/cpuinfo | grep processor | wc -l)
```

**Comment by demesm** [comment]
merged
